name: Build Preview

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build_android:
    name: Build Android
    type: build
    params:
      platform: android
      profile: preview

  build_ios:
    name: Build iOS
    type: build
    params:
      platform: ios
      profile: preview
